### ISSUE TITLE
mhcflurry-downloads fetches 0.9.1/models_class1 not 0.9.2 - update 

### ISSUE THREAD

**Issue by mhalagan-nmdp** [hammerlab/mhcflurry#105]
Running `pip install mhcflurry` and then `mhcflurry-downloads fetch` downloads **0.9.1/models_class1**. However, `Class1AffinityPredictor.load()` looks for **0.9.2/models_class1**.

```python
>>> from mhcflurry import Class1AffinityPredictor
>>> predictor = Class1AffinityPredictor.load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mhcflurry/class1_affinity_prediction/class1_affinity_predictor.py", line 186, in load
    models_dir = get_path("models_class1", "models")
  File "/mhcflurry/downloads.py", line 118, in get_path
    % (quote(path), download_name))
RuntimeError: Missing MHCflurry downloadable file: '/Users/mhalagan/Library/Application Support/mhcflurry/4/0.9.2/models_class1/models'. To download this data, run:
	mhcflurry-downloads fetch models_class1
in a shell.
```

The python package on PyPI must just be slightly out of date.

**Comment by timodonnell** [comment]
Thanks for the bug report @mhalagan-nmdp . I took a quick look and wasn't able to reproduce this. Is it possible that the MHCflurry library loaded in your import statement is the github master version, whereas the `mhcflurry-downloads` command is using the pip version?

In any case, I just pushed version 0.9.2 to [PyPI](https://travis-ci.org/hammerlab/mhcflurry/jobs/287619219), so please give that a try and let me know if you hit any more issues.

**Comment by timodonnell** [comment]
Does the new mhcflurry 1.0 package fix this for you @mhalagan-nmdp ? Closing for now, feel free to reopen.
