### ISSUE TITLE
Please bump Keras

### ISSUE THREAD

**Issue by jekriske-lilly** [hammerlab/mhcflurry#117]
Please bump Keras again or change the requirement to >=

**Comment by timodonnell** [comment]
It's bumped in PR #115 , which should get merged sometime in the next few days. Feel free to give that branch a shot if you'd like it sooner. That branch should be totally functional, all that's left is some docs I want to add before merging. Would appreciate any feedback if you hit any issues using the new version

**Comment by timodonnell** [comment]
We've been burned in the past with `>=` when keras was breaking backward compatibility with every version. Would be open to reconsidering now though

**Comment by timodonnell** [comment]
Requirement is now `tensorflow>=1.1.0` in the current master
