### ISSUE TITLE
Is there a way to download pre-trained networks to skip computationally intensive steps?

### ISSUE THREAD

**Issue by armish** [hammerlab/mhcflurry#2]
I am just following the steps on the README file and was wondering if there is any way to make the setup faster for a new user. Maybe we can delegate that to Travis and make it generate downloadable files for later use?

**Comment by iskandr** [comment]
Once I've fixed the instability of predictions (different initial weights -> different predictions on specific peptides), then we could put HDF files of all the models on dropbox (or hammerlab.org)

**Comment by iskandr** [comment]
@timodonnell @hammer Is Dropbox a good enough solution for now?

**Comment by iskandr** [comment]
I'm imagining we would have versioned model files (e.g. /mhcflurry/0.1/ALLELE-NAME.{json, hdf})

**Comment by hammer** [comment]
Hmm, we don't have a lab Dropbox account that I know about. Maybe stick them on the hammerlab.org Google Drive and put a link to the files on our website?

**Comment by iskandr** [comment]
@hammer I just meant my personal dropbox, which does seem sloppy/unsustainable. How do I access our Google drive? And can we download from it programmatically when installing mhcflurry?

**Comment by tavinathanson** [comment]
Do we know what the file size limit is for throwing these files into the PyPi upload?

**Comment by hammer** [comment]
@iskandr just log in with your alex@hammerlab.org address to access Google Drive. How big are the files though?

**Comment by hammer** [comment]
Another idea for how to get the model parameters to end users: we could use Sage Synapse, like Joel Dudley did for his IP Map paper: https://www.synapse.org/#!Synapse:syn4877787/files. From what I can tell, there are no limits on the size of the data we can upload.

**Comment by hammer** [comment]
Ah looks like the best way to get model parameters to users is to attach the HDF5 files to a release: https://help.github.com/articles/distributing-large-binaries/

**Comment by timodonnell** [comment]
This is now implemented
