### ISSUE TITLE
script/download-peters-2013-dataset.sh mentioned in README not present in scripts

### ISSUE THREAD

**Issue by vjcitn** [hammerlab/mhcflurry#29]
cloned today

%derby07> ls script
create-combined-class1-dataset.py
create-iedb-class1-dataset.py
download-iedb.sh
download-kim-2009-dataset.sh
download-kim-2013-dataset.sh
download-kim-blind-dataset.sh
mhcflurry-class1-web-server.py
mhcflurry-dataset-size-sensitivity.py
mhcflurry-predict-class1.py
mhcflurry-train-class1-allele-specific-models.py
print-class1-alleles.py

**Comment by hammer** [comment]
`download-peters-2013-dataset.sh` is no longer mentioned in the README
