### ISSUE TITLE
Move training data from Dropbox to S3 or something more permanent

### ISSUE THREAD

**Issue by maximz** [hammerlab/mhcflurry#33]
I'm referring to these downloads, which seem to fetch from Dropbox right now:
```
script/download-iedb.sh
script/download-kim-2013-dataset.sh
```

It'd be great to move those files to S3 so that we don't get burned by Dropbox's (undocumented?) limits on public file downloads.

**Comment by timodonnell** [comment]
This is fixed with the new `mhcflurry-downloads` command
