### ISSUE TITLE
Move feature engineering from scripts into module

### ISSUE THREAD

**Issue by hammer** [hammerlab/mhcflurry#39]
We should refactor our feature engineering code, as found in `create-iedb-class1-dataset.py` and `create-combined-class1-dataset.py`, into a library. This way we can run pipelines against raw data from IEDB and experiment with different feature engineering strategies. It's also easier to test library code.

**Comment by timodonnell** [comment]
We didn't actually make a library, but our "feature engineering" has gotten a lot simpler in the new release since we use all data now, so I'm closing this
