### ISSUE TITLE
Organize classifiers using mixins

### ISSUE THREAD

**Issue by iskandr** [hammerlab/mhcflurry#43]
We have a large combinatorial space of prediction problems which is hard to cover with linear inheritance for the predictor classes:
- Class I vs. Class II MHCs
- Pan-allele vs. allele-specific vs. multi-allele models
- Feed-forward networks with fixed vector encodings vs. variable length inputs with RNNs
- Regression (Affinity or stability prediction) vs. Classification (elution + mass spec)
- Convolutions over input sequence
- Cleavage prediction

One potential solution is to use mixin classes similar to [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/51a765a/sklearn/base.py#L281)

**Comment by timodonnell** [comment]
Not relevant in current codebase
