### ISSUE TITLE
Our model wrappers should document their constraints on models

### ISSUE THREAD

**Issue by hammer** [hammerlab/mhcflurry#44]
For example, `Class1AlleleSpecificKmerIC50PredictorBase.fit_dataset` will feed inputs of a certain shape into whatever model is passed to its constructor. We should document these constraints and check them at object creation time rather than model training time.

**Comment by hammer** [comment]
You should be able to check the input the model expects with `model.get_input_shape_at[0]`

**Comment by hammer** [comment]
More generally I'm having a really hard time figuring out what our universe of `fit_*` functions expect as input. For example, `Class1BindingPredictor.fit_kmer_encoded_arrays` says it expects `X` to be `Training data with shape (n_samples, n_dims)`. That's the syntax, but what about the semantics? To what should the `ndims` fields correspond?

**Comment by timodonnell** [comment]
Closed by #86
