### ISSUE TITLE
what are the units of your predictions?

### ISSUE THREAD

**Issue by flamholz** [hammerlab/mhcflurry#52]
Is the absolute value meaningful? Is it a -log(KD) or something? Can this be documented in the README? 

Avi

**Comment by timodonnell** [comment]
If you just call `predict`, the values returned are affinities (KD) in nM. Values < 500 are often considered "binders".

Internally, we actually predict a rescaled quantity:  1 - log(a)/log(50000) where `a` is the nM affinity. But users shouldn't have to interact with this rescaled quantity.

Does that answer your question?

**Comment by timodonnell** [comment]
Added a note to the readme

**Comment by flamholz** [comment]
Yup! Thanks for fast answer!

But it should be documented in the readme, since you give an example but
don't give units and it may not be apparent from that one example whether
the
(1) the prediction is relative or absolute (i.e. whether it has meaning in
the absence of a second prediction) and
(2) whether it is in uM, nM, fM units.

**Comment by flamholz** [comment]
I am satisfied and educated!
