### ISSUE TITLE
Data set grooming

### ISSUE THREAD

**Issue by hammer** [hammerlab/mhcflurry#6]
We've done some work in the past looking at weighting samples in IEDB based on our confidence in the quality of the measurement, and methods for collapsing multiple measurements for a (peptide, MHC) pair into a single training example. A recent [paper](http://discourse.hammerlab.org/t/automatic-generation-of-validated-specific-epitope-sets/206) (internal Discourse link) demonstrated the value in doing some grooming of IEDB to improve prediction quality. Perhaps we could lift performance a bit with some grooming?

**Comment by hammer** [comment]
@iskandr just noting that this came up in discussion with Neon today

**Comment by timodonnell** [comment]
Closed by #86
