### ISSUE TITLE
kreas has no attribute 'load_model'

### ISSUE THREAD

**Issue by ever4cyth** [hammerlab/mhcflurry#63]
predict(alleles=['A0201'], peptides=['SIINFEKL'])

    130             # it here before loading it into keras.
    131             fd.close()
--> 132             self.model = keras.models.load_model(fd.name)
    133         finally:
    134             os.unlink(fd.name)

AttributeError: 'module' object has no attribute 'load_model'

pip show keras
---
Metadata-Version: 1.1
Name: Keras
Version: 0.3.2
Summary: Deep Learning for Python
Home-page: https://github.com/fchollet/keras
Author: Francois Chollet
Author-email: francois.chollet@gmail.com
License: MIT
Location: /home/mongo/python/lib/python2.7/site-packages
Requires: theano, pyyaml, six
Classifiers:

**Comment by iskandr** [comment]
I suspect your version of Keras is out of date, since `load_model` seems to be in master: 

https://github.com/fchollet/keras/blob/90d0eb9b88c5ef6f756574f60d314c0aa7916f2c/keras/models.py#L97
