### ISSUE TITLE
error running test

### ISSUE THREAD

**Issue by bosmont** [hammerlab/mhcflurry#69]
hi,

I installed mhcflurry by following the instructions in the README.md:

`pip install mhcflurry`
`mhcflurry-downloads fetch`

when running 
`nosetests .`

 I got following error:

> ...
> Ran 47 tests in 254.464s
> FAILED (errors=14)
> Exception AttributeError: "'NoneType' object has no attribute 'TF_DeleteStatus'" in <bound method 
> Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f7366b1db90>> ignored

The similar error when running prediction command:
`mhcflurry-predict --alleles HLA-A0201 HLA-A0301 --peptides SIINFEKL SIINFEKD SIINFEKQ`

Using TensorFlow backend.
Predicting for 2 alleles and 3 peptides = 6 predictions
/home/ghost/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:91: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
allele,peptide,mhcflurry_prediction
HLA-A0201,SIINFEKL,10672.3476562
HLA-A0201,SIINFEKD,26042.7167969
HLA-A0201,SIINFEKQ,26375.7949219
HLA-A0301,SIINFEKL,25532.703125
HLA-A0301,SIINFEKD,24997.8769531
HLA-A0301,SIINFEKQ,28262.828125
Exception AttributeError: "'NoneType' object has no attribute 'TF_DeleteStatus'" in <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f2ad9c57090>> ignored

I googled around, but did not find any obvious solution.  Any help will be very much appreciated.

**Comment by timodonnell** [comment]
Thanks for the bug report @bosmont , and apologies for the late response. I just merged a PR that pins the keras version to a version we support (1.1.0). Can you try this now, after reinstalling MHCflurry and also setting `KERAS_BACKEND=theano`?

**Comment by timodonnell** [comment]
In the latest release (just pushed) we also now support tensorflow. Closing for now.
