### ISSUE TITLE
"ImportError: No module named numpy" when Installing mhcflurry

### ISSUE THREAD

**Issue by tinyheero** [hammerlab/mhcflurry#75]
Trying to install mhcflurry, but running into issues with it throwing an error. These were the commands I ran. First I created an isolated conda environment with python installed:

```
conda create -n mhcflurry python
```

```
source activate mhcflurry
export KERAS_BACKEND=theano
pip install mhcflurry
```

The following error occurred.

```
Collecting lxml (from pepdata->mhcflurry)
  Using cached lxml-3.7.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting ecos>=2 (from cvxpy->fancyimpute>=0.0.12->mhcflurry)
  Using cached ecos-2.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hqLDWd/ecos/setup.py", line 10, in <module>
        import numpy
    ImportError: No module named numpy
```

However, if I first install numpy:

```
pip install numpy
```

And then run:

```
pip install mhcflurry
```

This works. It seems that numpy is first required before installing mhcflurry. But I also see it part of the dependency list and downloaded when `pip install mhcflurry` is first called:

```
Collecting mhcflurry
  Using cached mhcflurry-0.0.8.tar.gz
Collecting numpy>=1.11 (from mhcflurry)
  Using cached numpy-1.11.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pandas>=0.13.1 (from mhcflurry)
  Using cached pandas-0.19.2-cp27-cp27mu-manylinux1_x86_64.whl
.
.
.
```

Not sure if the error that is happening is a byproduct of trying to install mhcflurry in a conda environment.

**Comment by timodonnell** [comment]
Not sure what was happening here @tinyheero but glad you were able to get it to work. Closing for now, please reopen if you hit it again
